---
title: "Resume"
author: "Qing Zhou"
date: 2019-01-31T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# SUMMARY

+	Skilled in Machine Learning and Deep Learning using Python Pandas, Scikit-learn, XGBoost, TensorFlow, and NLTK/CNTK package.
+ Proficient in Data Warehouse ETL and Quality Control using SAS, R, SQL Server, SSIS, Oracle, and Tableau.
+	Conscientious and self-directed with ability to manage multiple sophisticated projects while maintaining flexibility and accuracy within dynamic environments. <!--more-->

# JOB EXPERIENCE
1. **Kaiser Permanente Center for Health Research, Data Integration Specialist    Portland, OR| 2017-present**
+ Leading a company-wise initiative for extracting social history and quality of life information from unstructured clinical notes using Natural Language Processing (NLP).
+ Used Microsoft NLTK package to parse clinical notes to identify patient who had Local Reaction after vaccine injection. Compared to Ground Truth obtained by Chart Review, the positive predictive value (PPV) is 92%, specificity is 84%, and F1-score is 91%.
+ Introduced time series forecast algorithms in quality control of Data Warehouse daily refresh. Detected Anomalies in staging area and prevents bad data from leaking into production. This system has avoided loading more than 100 source errors in one year.
+ Wrote and distributed programs to do Quality Assessment on Data Warehouses in all Kaiser Permanente regions. Shorten the execution time while performing more checks. The Medical Encounter table in one big region contains 0.9 billion rows.
+ Improved the Error Handling of monitoring SSIS packages, which allows the whole Data Warehouse team to be able to check and respond to ETL error messages rather than just two people before. 

2. **Hack Oregon, Data Analyst (volunteer)     Portland, OR| 2016-2017**
+ Pulled Portland Fire & Rescue dispatch data from AWS EC2 instance. Explored the data, calculated response time, predicted False Alarms using Random Forests and visualized the analytical results in [Python Notebook](https://github.com/datascienceqing/PortlandFire).

3. **Molecular Testing Labs, Sr. Scientist      Vancouver, WA| 2013-2017**
+ Established a pharmacogenomics knowledge database in SQL Server for reporting purpose. The database was integrated into company’s Lab Information Management System (LIMS), which replaced the third party reporting service.
+ Managed 6 clinic trial data storage and analysis as assay development technical lead. 
+ Responded to doctors and clients to communicate the benefits of products.

4. **Oregon Health and Science University, Sr. Research Associate  Portland, OR| 2008-2013**
+ Collaborated with international teams to identify more than 50 mutations that cause Neonatal Diabetes, published 10 peer-reviewed scientific papers.

# PROJECTS
1. **Medicare PartD data set analysis  May 2017**
+ Performed data analysis on Medicare PartD data set using SAS. Demonstrated beneficiaries distribution, drug usage among specialties and state, as well as changes of providers between 2013 and 2014.
+ Compared the opioid description among female and male doctors in different states.[Link](https://github.com/datascienceqing/MedicareParD)
2. **Find Lane Lines    Feb 2017**
+ Used Python OpenCV module and Sliding Window algorithm to detect and mark Lane Lines and calculate curvature.[Link]( https://youtu.be/1VN5ryqO5r0)
3. **Find vehicles    Mar 2017**
+ Used Python OpenCV and Scikit-learn modules as well as Sliding Window algorithm to identify vehicles, then applied Heat map algorithm to filter out false calls and mark correct bounding boxes.[Link](https://youtu.be/tOZhbInBmNU )
4. **Clone Human Driving Behavior   Feb 2017**
+ Built an Nvidia end-to-end Convolutional Neural Network using Keras library to drive car in a simulator. Collected 10-minute data on the simulator then used the data to train the model. The model can drive the simulator car autonomously.[Link](https://youtu.be/5R_c7XdWmZg)
5. **Classify Traffic Signs   Jan 2017**
+ Built a Convolutional Neural Network using TensorFlow to classify traffic sign images in Python. Achieved 0.997 accuracy on 39,209 training images and 0.963 accuracy on 12,630 testing images.[Link](https://github.com/datascienceqing/Traffic-Sign-Classification-Project)

# EDUCATION& CERTIFICATE
+ Ph.D. in Microbiology, Wuhan University College of Life, Wuhan, China 2004-2007
+ SQL, Introduction to Apache Spark CS105x, Machine Learning,  Python Programming, R Programming, Java Programming and Software Engineering Fundamentals, Bayesian statistics,  Online Certificates   2015-2016  
+ SAS Base Programming Certificate for SAS 9 
+ SAS Advanced Programming Certificate for SAS 9
+ SAS Macro Language 2: Advanced Techniques, SAS Programming 2: Data Manipulation Techniques, SAS Programming 3: Advanced Techniques and Efficiencies, SAS Programming on the Grid, SAS programming for R Users, Hadoop data Management with Hive, Pig, and SAS, KP e-Learning Certificates 2017-2018 




